// <auto-generated />
using ApplyForLoanMicroservice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApplyForLoanMicroservice.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211005064825_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApplyForLoanMicroservice.Models.EducationLoanApplication", b =>
                {
                    b.Property<int>("applicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("annualIncome")
                        .HasColumnType("int");

                    b.Property<int>("courseFee")
                        .HasColumnType("int");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("fatherName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("fatherOccupation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("fathersCurCompanyExp")
                        .HasColumnType("int");

                    b.Property<int>("fathersTotalExp")
                        .HasColumnType("int");

                    b.Property<string>("interestRate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("loanAmount")
                        .HasColumnType("int");

                    b.Property<int>("loanPeriod")
                        .HasColumnType("int");

                    b.Property<long>("rationCardNo")
                        .HasColumnType("bigint");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("applicationId");

                    b.ToTable("EducationLoanApplications");
                });

            modelBuilder.Entity("ApplyForLoanMicroservice.Models.PersonalLoanApplication", b =>
                {
                    b.Property<int>("applicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("annualIncome")
                        .HasColumnType("int");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("expCurrentCompany")
                        .HasColumnType("int");

                    b.Property<string>("interestRate")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("loanAmount")
                        .HasColumnType("int");

                    b.Property<int>("loanPeriod")
                        .HasColumnType("int");

                    b.Property<int>("totalExp")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("applicationId");

                    b.ToTable("PersonalLoanApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
